import json
import logging
from pathlib import Path
from typing import Union

import nautilus_trader.model.instruments as instruments_module
from nautilus_trader.model.instruments import Instrument

logger = logging.getLogger(__name__)

def load_instrument(
    file_path: Union[str, Path],
) -> Instrument:
    """
    Loads an instrument from a JSON file.

    The JSON file is expected to be in the format generated by
    nautilus-practice/utils/fetch_instrument.py, which includes a "type" field
    specifying the Instrument subclass (e.g. "CryptoPerpetual").
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Instrument file not found: {path}")

    with open(path, "r") as f:
        data = json.load(f)

    instrument_type = data.get("type")
    if not instrument_type:
        raise ValueError(f"Invalid instrument data: missing 'type' field in {path}")

    # Dynamically get the class from the instruments module
    cls = getattr(instruments_module, instrument_type, None)

    if cls is None:
        raise ValueError(f"Unknown instrument type: {instrument_type}")

    # Verify it is indeed an Instrument subclass
    # Note: Some factory classes might not be direct subclasses, but usually we are looking for data classes
    if not issubclass(cls, Instrument):
        raise TypeError(f"Class {instrument_type} is not a subclass of Instrument")

    if not hasattr(cls, "from_dict"):
        raise ValueError(
            f"Instrument class {instrument_type} does not support from_dict deserialization"
        )

    # Fee handling: Binance provides fees in JSON, OKX does not
    # Default: maker 0.02%, taker 0.05% (typical perpetual contract fees)
    maker_fee = data.get("maker_fee")
    taker_fee = data.get("taker_fee")

    # 如果手续费缺失或为 0（OKX 常见情况），设置更符合实际的默认值（例如 maker 0.02%, taker 0.05%）
    if maker_fee is None or str(maker_fee) in ("0", "0.0") or float(maker_fee) == 0:
        data["maker_fee"] = "0.0002"
        logger.info("Maker fee is Unknown, set default values")
    if taker_fee is None or str(taker_fee) in ("0", "0.0") or float(taker_fee) == 0:
        data["taker_fee"] = "0.0005"
        logger.info("Taker fee is Unknown, set default values")

    return cls.from_dict(data)  # return a Instrument
